substitutions:
  devicename: "wipro-ns7001"

esphome:
  name: $devicename
  on_boot:
    priority: 700
    then:
      - light.turn_on:
          id: ns7001
          brightness: 100%
          white: 100%
          transition_length: 0s

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"
  reboot_timeout: 0s

ota:
  password: "xxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  power_save_mode: HIGH
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wipro-Ns7001 Fallback Hotspot"
    password: "xxxx"

captive_portal:

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5

light:
  - platform: rgbw
    name: $devicename
    id: ns7001
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    color_interlock: true 
    gamma_correct: 1.62
