esphome:
  name: l3-controller

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  password: "xxxx"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    bssid: 10:27:F5:xxxx
  reboot_timeout: 0s
  power_save_mode: high

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "L3-Controller Fallback Hotspot"
    password: "xxxx"

captive_portal:

status_led:
  pin:
    number: D4
    inverted: True

light:
  - platform: binary
    name: "l3-controller_light"
    output: relay1
    id: light1

switch:
  - platform: restart
    name: "l3-controller_module"

output:
  - platform: gpio
    pin: D6
    id: relay1

sun:
  latitude: 28.49521°
  longitude: 77.23225°    
  
  on_sunset:
    - then:
      - light.turn_on: light1
      
  on_sunrise:
    - then:
      - light.turn_off: light1
      
time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Kolkata
    on_time_sync:
      then:
        - if:
            condition:
              - sun.is_below_horizon:
            then:
              - light.turn_on: light1
            else:
              - light.turn_off: light1

text_sensor:
  - platform: sun
    name: Sun Next Sunrise
    type: sunrise
  - platform: sun
    name: Sun Next Sunset
    type: sunset
    
sensor:
  - platform: uptime
    name: l3_controller_uptime
    update_interval: 60s
